spring.application.name=notification-service
server.port=8084
spring.grpc.server.port=9084

# service discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# gRPC client to the driver websocket server (static address for local dev)
spring.grpc.client.websocket-server-driver.address=static://127.0.0.1:9101

# kafka
spring.kafka.bootstrap-servers=localhost:9092