spring.application.name=eureka-server
server.port=8761

# standalone registry: do not register/fetch from itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false