spring.application.name=api-gateway
server.port=8080

# env import line :
spring.config.import=optional:file:.env[.properties]

# jwt config :
security.jwt.secret-key=${SECRET_KEY:}
security.jwt.expiration-ms=8640000

# service discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# gRPC clients (static addresses for local dev; DiscoveryClient later)
spring.grpc.client.ride-service.address=static://127.0.0.1:9081
spring.grpc.client.websocket-server-rider.address=static://127.0.0.1:9100
spring.grpc.client.websocket-server-driver.address=static://127.0.0.1:9101