spring.application.name=websocket-server-driver
server.port=8091
spring.grpc.server.port=9101

# service discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.ridehailing.common.kafka.ProtobufSerializer